version: '3'

networks:
  log_generator_network:
    driver: bridge

services:
  web1:
    image: log_generator
    hostname: web1
    container_name: web1
    networks: 
      - log_generator_network
    volumes:
      - .:/app
    command: sh -c "rm -f /var/log/secure /var/log/access_log;python3 /app/log_generator.py -a /var/log/access_log -s /var/log/secure"
    extra_hosts:
      - "splunk.docker.internal:host-gateway"
  web2:
    image: log_generator
    hostname: web2
    container_name: web2
    networks: 
      - log_generator_network
    volumes:
      - .:/app
    command: sh -c "rm -f /var/log/secure /var/log/access_log;python3 /app/log_generator.py -a /var/log/access_log -s /var/log/secure"
    extra_hosts:
      - "splunk.docker.internal:host-gateway"
